apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mail
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: mail.localhost.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mail
                port:
                  name: ui
