grafana:
  adminUser: admin
  adminPassword: 8MBxR5x3mL0ZqH2t
  labels:
    grafana: primary
  persistence:
    size: 1Gi
  smtp:
    host: mail:1025
    fromAddress: grafana-alerts@example.com
    fromName: Grafana Alerts
    skipVerify: true
  alerting:
    emailTo: alerts@mailpit.local

datasources:
  loki:
    url: http://loki-gateway.loki.svc.cluster.local
    orgId: demo
  mimir:
    url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
    orgId: demo
    isDefault: true
  tempo:
    url: http://tempo-gateway.tempo.svc.cluster.local
    orgId: demo
