repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: minio
    url: https://operator.min.io

releases:
  - name: grafana-operator
    namespace: default
    chart: grafana/grafana-operator
    version: v5.20.0
    values:
      - values/grafana-operator.yaml

  - name: grafana-instance
    needs:
      - default/grafana-operator
    namespace: default
    chart: ./charts/grafana-instance
    version: 0.1.0
    values:
      - values/grafana-instance.yaml

  - name: mail
    namespace: default
    chart: ./charts/mail

  - name: minio-operator
    namespace: default
    chart: minio/operator
    version: 7.1.1
    wait: true

  - name: minio
    needs:
      - default/minio-operator
    namespace: default
    chart: minio/tenant
    version: 7.1.1
    values:
      - values/minio.yaml
    wait: true

  - name: mimir
    needs:
      - default/minio
    namespace: mimir
    chart: grafana/mimir-distributed
    version: 6.0.3
    values:
      - values/mimir.yaml

  - name: loki
    needs:
      - default/minio
    namespace: loki
    chart: grafana/loki
    version: 6.46.0
    values:
      - values/loki.yaml

  - name: tempo
    needs:
      - default/minio
    namespace: tempo
    chart: grafana/tempo-distributed
    version: 1.56.2
    values:
      - values/tempo.yaml

  - name: alloy
    namespace: default
    chart: grafana/alloy
    version: 1.4.0
    values:
      - values/alloy.yaml

  - name: app-1
    namespace: app
    chart: ./charts/app
    version: 0.1.0
    values:
      - values/app-1.yaml

  - name: app-2
    namespace: app
    chart: ./charts/app
    version: 0.1.0
    values:
      - values/app-2.yaml

  - name: k6-load
    namespace: app
    chart: ./charts/k6-load
    version: 0.1.0
    values:
      - values/k6-load.yaml
