grafana:
  version: 12.3.0
  name: grafana
  namespace: default
  labels:
    grafana: primary
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: ClusterIP
  alertmanager:
    enabled: true
    url: http://mimir-alertmanager.mimir.svc.cluster.local:9093
    orgId: demo
  smtp:
    enabled: true
    host: mail:1025
    fromAddress: grafana-alerts@example.com
    fromName: Grafana Alerts
    skipVerify: true
  alerting:
    emailTo: alerts@mailpit.local

datasources:
  loki:
    enabled: true
    url: http://loki-gateway.loki.svc.cluster.local
    orgId: demo
  mimir:
    enabled: true
    url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
    orgId: demo
    isDefault: true
  tempo:
    enabled: true
    url: http://tempo-query-frontend.tempo.svc.cluster.local:3100
    orgId: demo

demoAppObservability:
  enabled: true
  folderTitle: "Demo App Observability"
  prometheusDatasource: "mimir"
  lokiDatasource: "loki"
  tempoDatasource: "tempo"
