grafana:
  name: grafana
  namespace: default
  labels:
    grafana: primary
  adminUser: admin
  adminPassword: admin
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: ClusterIP

datasources:
  loki:
    enabled: true
    url: http://loki-gateway.loki.svc.cluster.local
    orgId: demo
  mimir:
    enabled: true
    url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
    orgId: demo
    isDefault: true
  tempo:
    enabled: true
    url: http://tempo-query-frontend.tempo.svc.cluster.local:3100
    orgId: demo
