apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-demo-app.fullname" . }}
  labels:
    {{- include "grafana-demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grafana-demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana-demo-app.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel | quote }}
            - name: APP_NAME
              value: {{ default .Release.Name .Values.env.appName | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otlpEndpoint | quote }}
            - name: CHAOS_SLOW_DB
              value: {{ .Values.env.chaosSlowDb | quote }}
            - name: CHAOS_ERROR
              value: {{ .Values.env.chaosError | quote }}
            - name: CHAOS_DB_FAILURE
              value: {{ .Values.env.chaosDbFailure | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
